# Generated by Django 5.0.6 on 2024-06-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virsliga2324',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vieta', models.CharField(db_column='Vieta', max_length=10)),
                ('komanda', models.CharField(db_column='Komanda', max_length=100)),
                ('spelets', models.IntegerField(db_column='Spēlēts')),
                ('uzvarets', models.IntegerField(db_column='Uzvarēts')),
                ('neizskirts', models.IntegerField(db_column='Neizšķirts')),
                ('zaudets', models.IntegerField(db_column='Zaudēts')),
                ('guti_varti', models.CharField(db_column='Gūti vārti', max_length=50)),
                ('plus_minus', models.IntegerField(db_column='+/-')),
                ('punkti', models.IntegerField(db_column='Punkti')),
            ],
            options={
                'db_table': 'virslīga 23_24',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(choices=[(1, 'ZRHK TENAX Dobele'), (2, 'MSĢ'), (3, 'ASK Zemessardze/LSPA'), (4, 'HK Ogre/HYDROX'), (5, 'Salaspils'), (6, 'HK Vaiņode'), (7, 'SK Latgols'), (8, 'HK S&A')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_id', models.IntegerField(choices=[(1, 'ZRHK TENAX Dobele'), (2, 'MSĢ'), (3, 'ASK Zemessardze/LSPA'), (4, 'HK Ogre/HYDROX'), (5, 'Salaspils'), (6, 'HK Vaiņode'), (7, 'SK Latgols'), (8, 'HK S&A')])),
                ('team2_id', models.IntegerField(choices=[(1, 'ZRHK TENAX Dobele'), (2, 'MSĢ'), (3, 'ASK Zemessardze/LSPA'), (4, 'HK Ogre/HYDROX'), (5, 'Salaspils'), (6, 'HK Vaiņode'), (7, 'SK Latgols'), (8, 'HK S&A')])),
                ('venue', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('team1_image', models.ImageField(upload_to='images/')),
                ('team2_image', models.ImageField(upload_to='images/')),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vieta', models.IntegerField()),
                ('spelets', models.IntegerField(default=0)),
                ('uzvarets', models.IntegerField(default=0)),
                ('neizskirts', models.IntegerField(default=0)),
                ('zaudets', models.IntegerField(default=0)),
                ('guti_varti', models.CharField(default='0:0', max_length=50)),
                ('plus_minus', models.IntegerField(default=0)),
                ('punkti', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handball.team')),
            ],
            options={
                'db_table': 'team_stats',
            },
        ),
    ]
