# Generated by Django 5.0.6 on 2024-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0002_teamstats_cumulative_goals_conceded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstats',
            name='guti_varti',
            field=models.CharField(default='0:0', max_length=50),
        ),
    ]
