# Generated by Django 5.0.6 on 2024-06-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0003_alter_teamstats_guti_varti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstats',
            name='guti_varti',
            field=models.CharField(default='0 : 0', max_length=20),
        ),
    ]
