# Generated by Django 5.0.6 on 2024-06-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0003_alter_upcominggame_team1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(choices=[(1, 'ZRHK TENAX Dobele'), (2, 'MSĢ'), (3, 'ASK Zemessardze/LSPA'), (4, 'HK Ogre/HYDROX'), (5, 'Salaspils'), (6, 'HK Vaiņode'), (7, 'SK Latgols'), (8, 'HK S&A')], max_length=100)),
            ],
        ),
    ]
