# Generated by Django 5.0.6 on 2024-06-06 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0004_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcominggame',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_games', to='handball.team'),
        ),
        migrations.AlterField(
            model_name='upcominggame',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_games', to='handball.team'),
        ),
    ]
