# Generated by Django 5.0.6 on 2024-06-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0004_alter_teamstats_guti_varti'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominggame',
            name='_stats_updated',
            field=models.BooleanField(default=False),
        ),
    ]
