# Generated by Django 5.0.6 on 2024-06-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0005_alter_upcominggame_team1_alter_upcominggame_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to='team_logos/'),
        ),
    ]
