# Generated by Django 5.0.6 on 2024-06-20 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0005_upcominggame__stats_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstats',
            old_name='team',
            new_name='team_id',
        ),
        migrations.AlterField(
            model_name='upcominggame',
            name='team1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_games_team1', to='handball.team'),
        ),
        migrations.AlterField(
            model_name='upcominggame',
            name='team2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_games_team2', to='handball.team'),
        ),
        migrations.CreateModel(
            name='PastGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('team1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_games_team1', to='handball.team')),
                ('team2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_games_team2', to='handball.team')),
            ],
        ),
    ]
