# Generated by Django 5.0.6 on 2024-06-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0006_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcominggame',
            name='team1_image',
        ),
        migrations.RemoveField(
            model_name='upcominggame',
            name='team2_image',
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(max_length=100),
        ),
    ]
