# Generated by Django 5.0.6 on 2024-06-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0006_rename_team_teamstats_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastgames',
            name='team1_image',
            field=models.ImageField(blank=True, null=True, upload_to='past_game_images/'),
        ),
        migrations.AddField(
            model_name='pastgames',
            name='team2_image',
            field=models.ImageField(blank=True, null=True, upload_to='past_game_images/'),
        ),
    ]
