# Generated by Django 5.0.6 on 2024-06-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0007_remove_upcominggame_team1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominggame',
            name='team1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='team2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
