# Generated by Django 5.0.6 on 2024-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0007_pastgames_team1_image_pastgames_team2_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandballPastgames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('team1_image', models.CharField(blank=True, max_length=100, null=True)),
                ('team2_image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'handball_pastgames',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PastGames',
        ),
    ]
