# Generated by Django 5.0.6 on 2024-06-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0008_upcominggame_team1_image_upcominggame_team2_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='upcominggame',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='upcominggame',
            name='team1_image',
        ),
        migrations.RemoveField(
            model_name='upcominggame',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='upcominggame',
            name='team2_image',
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='team1_id',
            field=models.IntegerField(choices=[(1, 'ZRHK TENAX Dobele'), (2, 'MSĢ'), (3, 'ASK Zemessardze/LSPA'), (4, 'HK Ogre/HYDROX'), (5, 'Salaspils'), (6, 'HK Vaiņode'), (7, 'SK Latgols'), (8, 'HK S&A')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='team1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos'),
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='team2_id',
            field=models.IntegerField(choices=[(1, 'ZRHK TENAX Dobele'), (2, 'MSĢ'), (3, 'ASK Zemessardze/LSPA'), (4, 'HK Ogre/HYDROX'), (5, 'Salaspils'), (6, 'HK Vaiņode'), (7, 'SK Latgols'), (8, 'HK S&A')], default=1132),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='team2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos'),
        ),
    ]
