# Generated by Django 5.0.6 on 2024-06-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0008_handballpastgames_delete_pastgames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handballpastgames',
            options={},
        ),
    ]
