# Generated by Django 5.0.6 on 2024-06-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0009_alter_handballpastgames_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='handballpastgames',
            name='team1_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='past_games_team1', to='handball.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handballpastgames',
            name='team2_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='past_games_team2', to='handball.team'),
            preserve_default=False,
        ),
    ]
