# Generated by Django 5.0.6 on 2024-06-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0009_remove_team_logo_remove_upcominggame_team1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcominggame',
            name='team1_logo',
        ),
        migrations.RemoveField(
            model_name='upcominggame',
            name='team2_logo',
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='team1_image',
            field=models.ImageField(default=3, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='team2_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
