# Generated by Django 5.0.6 on 2024-06-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0010_handballpastgames_team1_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handballpastgames',
            name='team1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='handballpastgames',
            name='team2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='upcominggame',
            table='upcoming_game',
        ),
    ]
