# Generated by Django 5.0.6 on 2024-06-07 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0011_alter_team_team_name_teamstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstats',
            name='guti_varti',
            field=models.CharField(max_length=50, default='35 : 98'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstats',
            name='neizskirts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstats',
            name='plus_minus',
            field=models.IntegerField(default=76),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstats',
            name='punkti',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstats',
            name='spelets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstats',
            name='uzvarets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstats',
            name='vieta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstats',
            name='zaudets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(choices=[(1, 'ZRHK TENAX Dobele'), (2, 'MSĢ'), (3, 'ASK Zemessardze/LSPA'), (4, 'HK Ogre/HYDROX'), (5, 'Salaspils'), (6, 'HK Vaiņode'), (7, 'SK Latgols'), (8, 'HK S&A')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handball.team'),
        ),
        migrations.AlterModelTable(
            name='teamstats',
            table='team_stats',
        ),
    ]
