# Generated by Django 5.0.6 on 2024-06-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0011_alter_handballpastgames_team1_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcominggame',
            old_name='_stats_updated',
            new_name='_moved_to_pastgames',
        ),
    ]
