# Generated by Django 5.0.6 on 2024-06-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0012_rename__stats_updated_upcominggame__moved_to_pastgames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcominggame',
            name='_moved_to_pastgames',
        ),
    ]
