# Generated by Django 5.0.6 on 2024-06-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0012_remove_teamstats_draws_remove_teamstats_games_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstats',
            name='guti_varti',
            field=models.CharField(max_length=50),
        ),
    ]
