# Generated by Django 5.0.6 on 2024-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball', '0013_remove_upcominggame__moved_to_pastgames'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominggame',
            name='_moved_to_pastgames',
            field=models.BooleanField(default=False),
        ),
    ]
